# Generated by Django 5.0.6 on 2024-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("thumbnail", models.ImageField(blank=True, upload_to="")),
                ("datatime", models.DateTimeField(blank=True)),
                ("source", models.CharField(max_length=128)),
                ("author", models.CharField(max_length=128)),
            ],
        ),
    ]
