# Generated by Django 5.0.6 on 2024-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketview", "0002_newslist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslist",
            name="datatime",
        ),
        migrations.AddField(
            model_name="newslist",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="newslist",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
