# Generated by Django 5.0.6 on 2024-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketview", "0003_remove_newslist_datatime_newslist_date_newslist_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslist",
            name="summary",
            field=models.CharField(default="...", max_length=256),
        ),
    ]
