# Generated by Django 5.0.6 on 2024-06-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketview", "0005_newstopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newstopic",
            name="topic",
            field=models.CharField(
                choices=[
                    ("blockchain", "Blockchain"),
                    ("earnings", "Earnings"),
                    ("ipo", "IPO"),
                    ("mergers_and_acquisitions", "Mergers & Acquisitions"),
                    ("financial_markets", "Financial Markets"),
                    ("economy_macro", "Economy"),
                    ("energy_transportation", "Energy & Transportation"),
                    ("finance", "Finance"),
                    ("life_sciences", "Life Sciences"),
                    ("manufacturing", "Manufacturing"),
                    ("real_estate", "Real Estate & Construction"),
                    ("retail_wholesale", "Retail & Wholesale"),
                    ("technology", "Technology"),
                ],
                max_length=30,
            ),
        ),
    ]
