# Generated by Django 5.0.6 on 2024-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketview", "0006_alter_newstopic_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslist",
            name="link",
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
